language: php

php:
    - 7.4

branches:
  only:
    - master

before_install:
    - sudo apt update
    - sudo apt install php7-imagick

before_script:
    - composer install

script:
    - phpcs --standard=PSR2
