
dist: bionic

language: php

php:
    - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo

#matrix:
#  allow_failures:
#    - php: 7.4

branches:
  only:
    - master

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
    - sudo apt update
    - sudo apt install php-imagick
    - pecl channel-update pecl.php.net
    - yes | pecl install imagick

    # install phpcs (remove after composer.lock update / use vendor package than)
    # see also: https://github.com/squizlabs/PHP_CodeSniffer
    - sudo apt install php-codesniffer

install:
  # install all of the dependencies you need here
  - composer install

before_script:
    # execute all of the commands which need to be executed
    # before running actual tests

script:
    # execute all of the commands which
    # should make the build pass or fail
    # - ./vendor/bin/phpcs --standard=PSR2 $(find ./ -name 'src/*.php')
    - phpcs --standard=PSR2 $(find ./src -name '*.php')
    - sudo composer test
