
dist: bionic

language: php

php:
    - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo

#matrix:
#  allow_failures:
#    - php: 7.4

branches:
  only:
    - master


before_install:
    - sudo apt update
    - sudo apt install php-imagick

before_script:
    - composer install

script:
    - phpcs --standard=PSR2 $(find ./ -name 'src/*.php')
