language: php
php:
    - 7.4
before_script:
    - pecl install imagick
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
script:
#    - phpunit
    - ./vendor/bin/phpcs
