language: php
php:
    - 7.4
before_install:
    sudo apt-get -y --reinstall install imagemagick
#    printf "\n" | pecl install imagick-beta
before_script:
#    - pecl install imagick
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
script:
#    - phpunit
    - phpcs --standard=PSR2
